# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='organisation',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
