# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20170129_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ('name',)},
        ),
    ]
